### ISSUE TITLE
Error running the train file

### ISSUE THREAD

**Issue by Peacepppp** [Ruyi-Zha/naf_cbct#3]
Hello, when I ran the train file, the following problems occurred, how can I solve it?
D:\Anaconda\envs\naf\python.exe E:/TIGRE/Python/naf_cbct/train.py
['E:\\TIGRE\\Python\\naf_cbct\\src\\encoder\\hashencoder\\src\\hashencoder.cu', 'E:\\TIGRE\\Python\\naf_cbct\\src\\encoder\\hashencoder\\src\\bindings.cpp']
Traceback (most recent call last):
  File "E:\TIGRE\Python\naf_cbct\train.py", line 14, in <module>
    from src.trainer import Trainer
  File "E:\TIGRE\Python\naf_cbct\src\trainer.py", line 12, in <module>
    from .encoder import get_encoder
  File "E:\TIGRE\Python\naf_cbct\src\encoder\__init__.py", line 1, in <module>
    from .hashencoder import HashEncoder
  File "E:\TIGRE\Python\naf_cbct\src\encoder\hashencoder\__init__.py", line 1, in <module>
    from .hashgrid import HashEncoder
  File "E:\TIGRE\Python\naf_cbct\src\encoder\hashencoder\hashgrid.py", line 8, in <module>
    from .backend import _backend
  File "E:\TIGRE\Python\naf_cbct\src\encoder\hashencoder\backend.py", line 6, in <module>
    _backend = load(name='_hash_encoder',
  File "D:\Anaconda\envs\naf\lib\site-packages\torch\utils\cpp_extension.py", line 1082, in load
    return _jit_compile(
  File "D:\Anaconda\envs\naf\lib\site-packages\torch\utils\cpp_extension.py", line 1320, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "D:\Anaconda\envs\naf\lib\site-packages\torch\utils\cpp_extension.py", line 1705, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
ImportError: DLL load failed while importing _hash_encoder: 找不到指定的模块。

Process finished with exit code 1

**Comment by Ruyi-Zha** [comment]
Hi, it seems an issue with the hash encoder. You may find solutions [here](https://github.com/ashawkey/torch-ngp/issues/29) or [here](https://github.com/ashawkey/torch-ngp/issues/26).

**Comment by Peacepppp** [comment]
Ok, thanks for your reply! I will try.

**Comment by amberhappy** [comment]
Same problem!
